### PR TITLE
Fix for the upstream filename change in easyrsa code

### PR DESCRIPTION
**Pull request by junaid-ali**
easyrsa conf file name is updated in upstream code in this commit[1]

    This change cater for this upstream commit and also includes the code at
    cs:etcd-8[2] which is being used in Calico bundles. There may have issues related
    to the revision and with the latest etcd charm because latest charm doesn't deploy
    etcd and easyrsa with a single charm rather we need to deploy easyrsa separately,
    and also easyrsa and etcd charms use juju resources to install specific versions of
    respective packages.

    [1]: https://github.com/OpenVPN/easy-rsa/commit/e8cd6c980742bb86c34286e655346778275cc36d
    [2]: https://jujucharms.com/etcd/8

Signed-off-by: Junaid Ali <junaidali.yahya@gmail.com>

### CODE REVIEW

**Comment by junaid-ali** [comment]
Other than copying the code from cs:etcd-8 in this repo, I only changed filename at these lines:

- https://github.com/projectcalico/charm-etcd/pull/1/commits/1434006a53bcecde3cff0426f8abb2e81bf7c476#diff-824d62511522aa1bf9816064d12a6a6cR48
- https://github.com/projectcalico/charm-etcd/pull/1/commits/1434006a53bcecde3cff0426f8abb2e81bf7c476#diff-824d62511522aa1bf9816064d12a6a6cR55

**Comment by junaid-ali** [comment]
@neiljerram

**Comment by nelljerram** [comment]
Hey @junaid-ali I'm finally looking at this - sorry to take so long about it!

The source for cs:etcd is elsewhere - I believe https://github.com/juju-solutions/layer-etcd - so you should propose this easyrsa name change there (unless it has already been made there).

(I'm sorry for not spotting and saying this earlier.  I had forgotten myself that projectcalico/charm-etcd is now obsoleted by the upstream etcd charm code!)

**Comment by junaid-ali** [comment]
Hi @neiljerram, thanks for looking into this pull request. I am aware that the latest etcd charm code is available at https://github.com/juju-solutions/layer-etcd  as you have already mentioned but there are now a lot of changes since the charm revision, **cs:etcd-8**, which is being used in Calico bundles. 

The latest version of etcd charm is **cs:etcd-59** which deploys a specific version of etcd ( a snap package available as a juju resource) while cs:etcd-8 deploys both etcd and easyrsa (latest) using the same charm. Also, installation of easyrsa is removed from latest upstream charm code and easyrsa is deployed with a different charm. If we use **cs:etcd-59**, then it will only deploy etcd and we have to deploy easyrsa with a separate charm which is **cs:~containers/easyrsa-23** (https://github.com/juju-solutions/layer-easyrsa).

I have pushed fix for easyrsa in this pull request but this fix can't be pushed to upstream easyrsa charm code for now since the latest easyrsa charm uses an older version of easyrsa package (as a tar file using juju resources)

I know it's a bit complex situation here due to the separation of easyrsa and etcd into two different charms, and I would need your suggestion regarding how we can fix the **broken Calico deployment** due to the upstream commit in easyrsa package.

Please let me know if you have any confusion or if you need further explanation about the issue.

**Pull request closed without merging**
